{% set name = "iexfinance" %}
{% set version = "0.3.5" %}
{% set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e2643c7583d877fd55d24cf4a3d1173d761b42bd66a926734436a95d148f52b

build:
  number: {{ build_num }}
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pandas
    - requests

test:
  imports:
    - iexfinance

about:
  home: http://github.com/addisonlynch/iexfinance
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'Python wrapper for The Investors Exchange (IEX) Developer API'

  description: |
    An easy-to-use Python interface to the IEX developer API to obtain
    real-time equities data, including quotes, historical prices, fundamentals,
    actions (splits/dividends), trading analyses (gainers, losers, etc), and
    IEX market data and statistics.
  doc_url: http://addisonlynch.github.io/iexfinance/stable
  dev_url: https://github.com/addisonlynch/iexfinance

extra:
  recipe-maintainers:
    - addisonlynch
